"""
Score prompt-sensitivity manuscript variants with the saved local AI-like detector.

This is a zero-cost complement to commercial AIGC detector checks. The scores
are classifier probabilities under this project's training definition:

    y=1: abstracts generated by LLMs from metadata
    y=0: real published abstracts

Therefore, the output should be reported as a local AI-like score, not as a
measured percentage of true AI authorship.
"""

from __future__ import annotations

import argparse
import csv
import math
import re
from collections import Counter
from pathlib import Path
from typing import Any


STYLE_FEATURES = [
    "computed_word_count",
    "sentence_count",
    "sentence_length_mean",
    "sentence_length_std",
    "lexical_diversity",
    "hapax_ratio",
    "bigram_repetition",
    "trigram_repetition",
    "connector_ratio",
    "template_phrase_count",
    "punctuation_ratio",
    "token_entropy",
]

TOKEN_RE = re.compile(r"[A-Za-z]+(?:[-'][A-Za-z]+)?|\d+(?:\.\d+)?")
SENTENCE_RE = re.compile(r"(?<=[.!?。！？])\s*")
ACADEMIC_CONNECTORS = {
    "therefore",
    "however",
    "moreover",
    "furthermore",
    "nevertheless",
    "consequently",
    "thus",
    "hence",
    "whereas",
    "although",
    "because",
    "since",
    "while",
    "overall",
    "finally",
}
TEMPLATE_PHRASES = [
    "the purpose of this study",
    "this study aims",
    "this paper presents",
    "the results show",
    "the results showed",
    "in this paper",
    "in this study",
    "we propose",
    "we investigated",
    "we examined",
    "it is concluded",
    "this article examines",
    "本文旨在",
    "结果表明",
    "研究表明",
    "进一步提示",
    "需要指出的是",
    "本文认为",
    "本文发现",
    "实验结果表明",
]


# These two functions intentionally match names used by train_local_ai_detector.py.
# Saved joblib pipelines may refer to __main__.abstract_list/style_matrix.
def to_float(value: str) -> float:
    try:
        return float(value)
    except (TypeError, ValueError):
        return 0.0


def style_matrix(rows: list[dict[str, str]]) -> list[list[float]]:
    return [[to_float(row.get(name, "")) for name in STYLE_FEATURES] for row in rows]


def abstract_list(rows: list[dict[str, str]]) -> list[str]:
    return [row.get("abstract", "") for row in rows]


def tokenize(text: str) -> list[str]:
    return [token.lower() for token in TOKEN_RE.findall(text)]


def split_sentences(text: str) -> list[str]:
    parts = [part.strip() for part in SENTENCE_RE.split(text.strip()) if part.strip()]
    return parts or ([text.strip()] if text.strip() else [])


def ngram_repetition(tokens: list[str], n: int) -> float:
    if len(tokens) < n:
        return 0.0
    ngrams = [tuple(tokens[i : i + n]) for i in range(len(tokens) - n + 1)]
    counts = Counter(ngrams)
    repeated = sum(count - 1 for count in counts.values() if count > 1)
    return repeated / max(len(ngrams), 1)


def shannon_entropy(tokens: list[str]) -> float:
    if not tokens:
        return 0.0
    counts = Counter(tokens)
    total = len(tokens)
    return -sum((count / total) * math.log2(count / total) for count in counts.values())


def features_for_text(text: str) -> dict[str, str]:
    tokens = tokenize(text)
    sentences = split_sentences(text)
    sentence_lengths = [len(tokenize(sentence)) for sentence in sentences]
    lower_text = text.lower()

    mean_len = sum(sentence_lengths) / len(sentence_lengths) if sentence_lengths else 0.0
    if len(sentence_lengths) > 1:
        variance = sum((length - mean_len) ** 2 for length in sentence_lengths) / (len(sentence_lengths) - 1)
        std_len = math.sqrt(variance)
    else:
        std_len = 0.0

    connector_count = sum(1 for token in tokens if token in ACADEMIC_CONNECTORS)
    template_count = sum(1 for phrase in TEMPLATE_PHRASES if phrase in lower_text)
    punctuation_count = sum(1 for char in text if char in ",;:()[]，；：（）【】")

    return {
        "computed_word_count": str(len(tokens)),
        "sentence_count": str(len(sentences)),
        "sentence_length_mean": f"{mean_len:.4f}",
        "sentence_length_std": f"{std_len:.4f}",
        "lexical_diversity": f"{(len(set(tokens)) / len(tokens)) if tokens else 0.0:.4f}",
        "hapax_ratio": f"{(sum(1 for count in Counter(tokens).values() if count == 1) / len(tokens)) if tokens else 0.0:.4f}",
        "bigram_repetition": f"{ngram_repetition(tokens, 2):.4f}",
        "trigram_repetition": f"{ngram_repetition(tokens, 3):.4f}",
        "connector_ratio": f"{(connector_count / len(tokens)) if tokens else 0.0:.4f}",
        "template_phrase_count": str(template_count),
        "punctuation_ratio": f"{(punctuation_count / len(text)) if text else 0.0:.4f}",
        "token_entropy": f"{shannon_entropy(tokens):.4f}",
    }


def read_variants(variants_dir: Path) -> list[dict[str, str]]:
    files = sorted(variants_dir.glob("*.md"))
    if not files:
        raise SystemExit(f"No .md files found in {variants_dir}")

    rows: list[dict[str, str]] = []
    for file_path in files:
        text = file_path.read_text(encoding="utf-8-sig").strip()
        row = {
            "variant_id": file_path.stem,
            "file_path": str(file_path),
            "abstract": text,
            "char_count": str(len(text)),
        }
        row.update(features_for_text(text))
        rows.append(row)
    return rows


def load_models(model_dir: Path) -> dict[str, Any]:
    try:
        import joblib
    except ImportError as exc:
        raise SystemExit(
            "Missing dependency: joblib/scikit-learn.\n"
            "Install once with:\n"
            "  python -m pip install scikit-learn joblib"
        ) from exc

    model_paths = {
        "text_tfidf_logreg": model_dir / "text_tfidf_logreg.joblib",
        "style_logreg": model_dir / "style_logreg.joblib",
        "combined_logreg": model_dir / "combined_logreg.joblib",
    }
    missing = [str(path) for path in model_paths.values() if not path.exists()]
    if missing:
        raise SystemExit("Missing model files:\n" + "\n".join(missing))

    return {name: joblib.load(path) for name, path in model_paths.items()}


def score_rows(rows: list[dict[str, str]], models: dict[str, Any]) -> list[dict[str, str]]:
    for name, model in models.items():
        if name == "text_tfidf_logreg":
            X = [row["abstract"] for row in rows]
        else:
            X = rows
        scores = model.predict_proba(X)[:, 1]
        for row, score in zip(rows, scores):
            row[f"{name}_ai_like_score"] = f"{float(score):.6f}"
    return rows


def write_csv(path: Path, rows: list[dict[str, str]]) -> None:
    fieldnames: list[str] = []
    for row in rows:
        for key in row:
            if key not in fieldnames:
                fieldnames.append(key)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8-sig", newline="") as file:
        writer = csv.DictWriter(file, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def write_summary(path: Path, rows: list[dict[str, str]], main_score: str) -> None:
    sorted_rows = sorted(rows, key=lambda row: row.get("variant_id", ""))
    score_keys = [
        "text_tfidf_logreg_ai_like_score",
        "style_logreg_ai_like_score",
        "combined_logreg_ai_like_score",
    ]
    lines = [
        "# 本地检测器提示词敏感性评分",
        "",
        "说明：以下分数来自本文训练的本地 AI-like 检测器，表示文本接近“AI从元数据生成摘要”训练正例的程度，不能解释为真实 AI 参与比例。",
        "",
        "注意：该检测器训练语料主要是英文论文摘要；若输入为中文完整论文，分数属于跨语言、跨体裁、跨长度的出域评分，应优先用于同一设置下的相对比较。",
        "",
        "| 版本 | Text TF-IDF | Style | Combined | 字符数 | 模板短语数 |",
        "|---|---:|---:|---:|---:|---:|",
    ]
    for row in sorted_rows:
        lines.append(
            f"| {row.get('variant_id', '')} "
            f"| {float(row.get('text_tfidf_logreg_ai_like_score', 0)):.6f} "
            f"| {float(row.get('style_logreg_ai_like_score', 0)):.6f} "
            f"| {float(row.get('combined_logreg_ai_like_score', 0)):.6f} "
            f"| {row.get('char_count', '')} "
            f"| {row.get('template_phrase_count', '')} |"
        )

    scored = [(row.get("variant_id", ""), float(row.get(main_score, 0))) for row in sorted_rows]
    if len(scored) >= 2:
        highest = max(scored, key=lambda item: item[1])
        lowest = min(scored, key=lambda item: item[1])
        spread = highest[1] - lowest[1]
        text_scores = [
            (row.get("variant_id", ""), float(row.get("text_tfidf_logreg_ai_like_score", 0)))
            for row in sorted_rows
        ]
        text_highest = max(text_scores, key=lambda item: item[1])
        text_lowest = min(text_scores, key=lambda item: item[1])
        text_spread = text_highest[1] - text_lowest[1]
        lines.extend(
            [
                "",
                "## 可写入论文的结论句",
                "",
            ]
        )
        if spread > 1e-6:
            lines.append(
                f"在本地 AI-like 检测器中，不同提示词版本的 combined 分数存在差异："
                f"最高版本为 `{highest[0]}`（{highest[1]:.6f}），"
                f"最低版本为 `{lowest[0]}`（{lowest[1]:.6f}），"
                f"差值为 {spread:.6f}。"
                "该结果提示，即便文本主题和核心事实保持不变，提示词诱导的写作风格变化也可能改变检测器输出。"
            )
        else:
            lines.append(
                "在本地 AI-like 检测器中，各提示词版本的 combined 分数几乎没有差异。"
                "考虑到该检测器训练于英文摘要，而当前输入为中文完整论文，这一结果更可能反映跨语言、跨体裁使用导致的出域失效，"
                "不宜据此判断提示词对 AIGC 率没有影响。"
            )
        lines.append(
            f"作为参考，Text TF-IDF 分数最高版本为 `{text_highest[0]}`（{text_highest[1]:.6f}），"
            f"最低版本为 `{text_lowest[0]}`（{text_lowest[1]:.6f}），"
            f"差值为 {text_spread:.6f}。"
            "该分数同样不能解释为 AIGC 率，只能作为同一出域检测器下的弱相对指标。"
        )

    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--variants-dir", default="prompt_sensitivity_experiment/variants")
    parser.add_argument("--model-dir", default="local_detector_results_budget_grouped_v2")
    parser.add_argument("--out-csv", default="prompt_sensitivity_experiment/local_detector_scores.csv")
    parser.add_argument("--out-md", default="prompt_sensitivity_experiment/local_detector_scores_summary.md")
    args = parser.parse_args()

    rows = read_variants(Path(args.variants_dir))
    models = load_models(Path(args.model_dir))
    scored_rows = score_rows(rows, models)
    write_csv(Path(args.out_csv), scored_rows)
    write_summary(Path(args.out_md), scored_rows, "combined_logreg_ai_like_score")
    print(f"Scored {len(scored_rows)} variants.")
    print(f"Wrote {args.out_csv}")
    print(f"Wrote {args.out_md}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
